"""Agent 执行过程的运行、结果、消息、事件与证据领域合同。"""

from app.domain.execution.artifacts import Artifact, ArtifactType
from app.domain.execution.events import (
    RUN_EVENT_ADAPTER,
    CycleStartedEvent,
    ExecutionErrorEvent,
    MessageAppendedEvent,
    MessageValidationFailedEvent,
    RunEvent,
    RunEventBase,
    RunLifecycleEvent,
    StoredRunEvent,
    TaskLifecycleEvent,
    TasksSkippedEvent,
    ToolStartedEvent,
)
from app.domain.execution.messages import (
    RunAIMessage,
    RunContentBlock,
    RunHumanMessage,
    RunImageArtifactBlock,
    RunInvalidToolCall,
    RunMessage,
    RunSystemMessage,
    RunTextBlock,
    RunToolCall,
    RunToolMessage,
)
from app.domain.execution.runs import (
    ReasonCode,
    TaskAgentCompletion,
    TaskRun,
    TaskRunResult,
    TaskRunStatus,
    TestRun,
    TestRunDetail,
    TestRunSnapshot,
    TestRunStatus,
    TestRunVerdict,
    aggregate_test_run_verdict,
)

__all__ = [
    "Artifact",
    "ArtifactType",
    "CycleStartedEvent",
    "ExecutionErrorEvent",
    "MessageAppendedEvent",
    "MessageValidationFailedEvent",
    "RUN_EVENT_ADAPTER",
    "ReasonCode",
    "RunAIMessage",
    "RunContentBlock",
    "RunEvent",
    "RunEventBase",
    "RunHumanMessage",
    "RunImageArtifactBlock",
    "RunInvalidToolCall",
    "RunLifecycleEvent",
    "RunMessage",
    "RunSystemMessage",
    "RunTextBlock",
    "RunToolCall",
    "RunToolMessage",
    "StoredRunEvent",
    "TaskAgentCompletion",
    "TaskLifecycleEvent",
    "TaskRun",
    "TaskRunResult",
    "TaskRunStatus",
    "TasksSkippedEvent",
    "TestRun",
    "TestRunDetail",
    "TestRunSnapshot",
    "TestRunStatus",
    "TestRunVerdict",
    "ToolStartedEvent",
    "aggregate_test_run_verdict",
]
