/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_api_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_api_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device */
        get: operations["get_device_api_devices__device_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Test Runs */
        get: operations["list_test_runs_api_runs_get"];
        put?: never;
        /** Create Test Run */
        post: operations["create_test_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{test_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Test Run */
        get: operations["get_test_run_api_runs__test_run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{test_run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Test Run */
        post: operations["cancel_test_run_api_runs__test_run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{test_run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Run Events */
        get: operations["list_run_events_api_runs__test_run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{test_run_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Test Run Report */
        post: operations["export_test_run_report_api_runs__test_run_id__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{test_run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Test Run Report */
        get: operations["get_test_run_report_api_runs__test_run_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{test_run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run Events */
        get: operations["stream_run_events_api_runs__test_run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Test Cases */
        get: operations["list_test_cases_api_test_cases_get"];
        put?: never;
        /** Create Test Case */
        post: operations["create_test_case_api_test_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test-cases/{test_case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Test Case */
        get: operations["get_test_case_api_test_cases__test_case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test-cases/{test_case_id}/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Test Plans */
        get: operations["list_test_plans_api_test_cases__test_case_id__plans_get"];
        put?: never;
        /** Generate Plan */
        post: operations["generate_plan_api_test_cases__test_case_id__plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test-plans/{test_plan_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revise Test Plan */
        post: operations["revise_test_plan_api_test_plans__test_plan_id__revisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentActivity
         * @description Agent 正在执行的稳定活动，用于模型路由和工具授权。
         * @enum {string}
         */
        AgentActivity: "planning" | "act" | "judge";
        /** ApiError */
        ApiError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /**
         * Artifact
         * @description 已持久化文件的公开元数据；原始路径和文件 bytes 不进入领域合同。
         */
        Artifact: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Mime Type */
            mime_type: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Task Run Id */
            task_run_id: string | null;
            /** Test Run Id */
            test_run_id: string | null;
            type: components["schemas"]["ArtifactType"];
        };
        /**
         * ArtifactType
         * @description Artifact 的业务用途，决定其直接所有者和内容消费方式。
         * @enum {string}
         */
        ArtifactType: "screenshot" | "json_export" | "html_export";
        /**
         * CycleStartedEvent
         * @description TaskAgent 开始一个新观察 cycle 的计数事实。
         */
        CycleStartedEvent: {
            /** Cycle Count */
            cycle_count: number;
            /** Task Run Id */
            task_run_id: string | null;
            /** Test Run Id */
            test_run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "cycle.started";
        };
        /**
         * DeviceEnvironmentSnapshot
         * @description TestRun 创建时冻结的设备提供方、描述与健康状态。
         */
        DeviceEnvironmentSnapshot: {
            health: components["schemas"]["DeviceHealth"];
            info: components["schemas"]["DeviceInfo"] | null;
            /** Provider */
            provider: string;
        };
        /**
         * DeviceHealth
         * @description 一次实时健康检查结果，由 DeviceProvider 产生并供 API/运行创建消费。
         */
        DeviceHealth: {
            /** Available */
            available: boolean;
            /** Message */
            message: string;
        };
        /**
         * DeviceInfo
         * @description 可复用的设备客观描述，不包含连接凭据或运行生命周期状态。
         */
        DeviceInfo: {
            /** Locale */
            locale: string | null;
            /** Model */
            model: string | null;
            /** Resolution */
            resolution: string | null;
        };
        /**
         * DeviceResponse
         * @description HTTP 设备查询响应；由 route 从实时设备和工具 provider 投影。
         */
        DeviceResponse: {
            /** Device Id */
            device_id: string;
            health: components["schemas"]["DeviceHealth"];
            info: components["schemas"]["DeviceInfo"] | null;
            /** Provider */
            provider: string;
            tool_catalog: components["schemas"]["ToolCatalogSnapshot"] | null;
        };
        /**
         * ExecutionErrorEvent
         * @description 阻塞执行的基础设施或协议错误。
         */
        ExecutionErrorEvent: {
            /** Message */
            message: string;
            reason_code: components["schemas"]["ReasonCode"];
            /** Task Run Id */
            task_run_id: string | null;
            /** Test Run Id */
            test_run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "execution.error";
        };
        /** GeneratePlanRequest */
        GeneratePlanRequest: {
            /** Device Id */
            device_id: string;
        };
        /**
         * LLMProfileSnapshot
         * @description 一次模型客户端配置的脱敏投影；TestPlan/TestRun 用它冻结实际选择。
         */
        LLMProfileSnapshot: {
            /** Base Url */
            base_url: string | null;
            /** Characters Per Token */
            characters_per_token: number;
            /** Context Safety Margin Tokens */
            context_safety_margin_tokens: number;
            /** Context Window Tokens */
            context_window_tokens: number;
            /** Max Output Tokens */
            max_output_tokens: number;
            /** Model */
            model: string;
            /** Profile Id */
            profile_id: string;
            /** Provider */
            provider: string;
            /** Temperature */
            temperature: number;
            /** Timeout Seconds */
            timeout_seconds: number;
            /** Tokens Per Image */
            tokens_per_image: number;
        };
        /**
         * MessageAppendedEvent
         * @description Graph Message 首次成为公开、持久事实。
         */
        MessageAppendedEvent: {
            /** Message */
            message: components["schemas"]["RunSystemMessage"] | components["schemas"]["RunHumanMessage"] | components["schemas"]["RunAIMessage"] | components["schemas"]["RunToolMessage"];
            /** Task Run Id */
            task_run_id: string | null;
            /** Test Run Id */
            test_run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "message.appended";
        };
        /**
         * MessageValidationFailedEvent
         * @description 模型消息未通过单工具调用协议校验。
         */
        MessageValidationFailedEvent: {
            /** Attempt */
            attempt: number;
            /** Message Id */
            message_id: string;
            /** Reason */
            reason: string;
            /** Task Run Id */
            task_run_id: string | null;
            /** Test Run Id */
            test_run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "message.validation_failed";
        };
        /** PageResponse[DeviceResponse] */
        PageResponse_DeviceResponse_: {
            /** Items */
            items: components["schemas"]["DeviceResponse"][];
            /** Total */
            total: number;
        };
        /** PageResponse[StoredRunEvent] */
        PageResponse_StoredRunEvent_: {
            /** Items */
            items: components["schemas"]["StoredRunEvent"][];
            /** Total */
            total: number;
        };
        /** PageResponse[TestCase] */
        PageResponse_TestCase_: {
            /** Items */
            items: components["schemas"]["TestCase"][];
            /** Total */
            total: number;
        };
        /** PageResponse[TestPlan] */
        PageResponse_TestPlan_: {
            /** Items */
            items: components["schemas"]["TestPlan"][];
            /** Total */
            total: number;
        };
        /** PageResponse[TestRun] */
        PageResponse_TestRun_: {
            /** Items */
            items: components["schemas"]["TestRun"][];
            /** Total */
            total: number;
        };
        /**
         * ReasonCode
         * @description TaskRun/执行错误的稳定结果原因；它是持久化事实而非异常类型。
         * @enum {string}
         */
        ReasonCode: "completed" | "assertion_failed" | "goal_unreachable" | "cycle_limit" | "device_unavailable" | "capture_failed" | "model_unavailable" | "invalid_model_response" | "agent_blocked" | "tool_failed" | "process_restarted" | "global_fail_fast" | "user_cancelled" | "prompt_version_mismatch" | "model_profile_mismatch" | "model_context_exceeded" | "unexpected_error";
        /** ReportExportRequest */
        ReportExportRequest: {
            /**
             * Format
             * @enum {string}
             */
            format: "json" | "html";
        };
        /** ReviseTestPlanRequest */
        ReviseTestPlanRequest: {
            content: components["schemas"]["TestPlanContent_TestTaskDefinition_"];
        };
        /**
         * RunAIMessage
         * @description 模型回复及其工具调用事实的公开投影。
         */
        RunAIMessage: {
            /** Content */
            content: (components["schemas"]["RunTextBlock"] | components["schemas"]["RunImageArtifactBlock"])[];
            /** Invalid Tool Calls */
            invalid_tool_calls: components["schemas"]["RunInvalidToolCall"][];
            /** Message Id */
            message_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "ai";
            /** Tool Calls */
            tool_calls: components["schemas"]["RunToolCall"][];
        };
        /**
         * RunHumanMessage
         * @description 用户/运行时上下文和截图观察的公开投影。
         */
        RunHumanMessage: {
            /** Content */
            content: (components["schemas"]["RunTextBlock"] | components["schemas"]["RunImageArtifactBlock"])[];
            /** Message Id */
            message_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "human";
        };
        /**
         * RunImageArtifactBlock
         * @description 公开消息中的截图证据引用；不会复制图片 base64。
         */
        RunImageArtifactBlock: {
            /** Artifact Id */
            artifact_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "image_artifact";
        };
        /**
         * RunInvalidToolCall
         * @description LangChain 已定型 InvalidToolCall 的稳定公开字段。
         */
        RunInvalidToolCall: {
            /** Arguments */
            arguments: string | null;
            /** Error */
            error: string | null;
            /** Id */
            id: string | null;
            /** Name */
            name: string | null;
        };
        /**
         * RunLifecycleEvent
         * @description TestRun 生命周期改变的通知事实，不复制实体字段。
         */
        RunLifecycleEvent: {
            /** Task Run Id */
            task_run_id: string | null;
            /** Test Run Id */
            test_run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.cancelled" | "run.finished" | "run.started";
        };
        /**
         * RunSystemMessage
         * @description TaskAgent 实际使用的系统指令公开投影。
         */
        RunSystemMessage: {
            /** Content */
            content: (components["schemas"]["RunTextBlock"] | components["schemas"]["RunImageArtifactBlock"])[];
            /** Message Id */
            message_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "system";
        };
        /**
         * RunTextBlock
         * @description 公开消息中的纯文本内容块。
         */
        RunTextBlock: {
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
        };
        /**
         * RunToolCall
         * @description 模型发出的一个已解析工具调用。
         */
        RunToolCall: {
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * RunToolMessage
         * @description 框架工具执行结果的公开投影。
         */
        RunToolMessage: {
            /** Content */
            content: (components["schemas"]["RunTextBlock"] | components["schemas"]["RunImageArtifactBlock"])[];
            /** Message Id */
            message_id: string;
            /** Name */
            name: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "tool";
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "error";
            /** Tool Call Id */
            tool_call_id: string;
        };
        /**
         * StoredRunEvent
         * @description 事件存储分配的 ID、顺序和时间与 canonical 事件的统一 envelope。
         */
        StoredRunEvent: {
            /** Event */
            event: components["schemas"]["MessageAppendedEvent"] | components["schemas"]["MessageValidationFailedEvent"] | components["schemas"]["RunLifecycleEvent"] | components["schemas"]["TaskLifecycleEvent"] | components["schemas"]["CycleStartedEvent"] | components["schemas"]["ToolStartedEvent"] | components["schemas"]["ExecutionErrorEvent"] | components["schemas"]["TasksSkippedEvent"];
            /** Event Id */
            event_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Sequence */
            sequence: number;
        };
        /**
         * TaskLifecycleEvent
         * @description TaskRun 启动或结束的通知事实。
         */
        TaskLifecycleEvent: {
            /** Task Run Id */
            task_run_id: string | null;
            /** Test Run Id */
            test_run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "task.finished" | "task.started";
        };
        /**
         * TaskRun
         * @description 真正启动或由 fail-fast 跳过的单个计划任务执行实体。
         */
        TaskRun: {
            /** Cycle Count */
            cycle_count: number;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            result: components["schemas"]["TaskRunResult"] | null;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["TaskRunStatus"];
            /** Test Run Id */
            test_run_id: string;
            /** Test Task Id */
            test_task_id: string;
        };
        /**
         * TaskRunResult
         * @description TaskRun 的终态原因、摘要与证据引用；状态和 cycle 不在此重复。
         */
        TaskRunResult: {
            /** Evidence Artifact Ids */
            evidence_artifact_ids: string[];
            reason_code: components["schemas"]["ReasonCode"];
            /** Summary */
            summary: string;
        };
        /**
         * TaskRunStatus
         * @description 已创建 TaskRun 的生命周期或终态；cancelled 表示启动后被用户终止。
         * @enum {string}
         */
        TaskRunStatus: "running" | "passed" | "failed" | "blocked" | "skipped" | "cancelled";
        /**
         * TasksSkippedEvent
         * @description 全局 fail-fast 批量创建未执行 TaskRun 的事实。
         */
        TasksSkippedEvent: {
            /** Task Run Id */
            task_run_id: string | null;
            /** Task Run Ids */
            task_run_ids: string[];
            /** Test Run Id */
            test_run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tasks.skipped";
        };
        /**
         * TestCase
         * @description 测试意图的持久化实体；后续 TestPlan 版本通过 ID 归属于它。
         */
        TestCase: {
            content: components["schemas"]["TestCaseContent"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
        };
        /**
         * TestCaseContent
         * @description 用户提交的测试意图；由 TestCase 和规划上下文共同复用。
         */
        TestCaseContent: {
            /** Name */
            name: string;
            /** Source Text */
            source_text: string;
        };
        /**
         * TestCaseCreateRequest
         * @description Command name over the canonical TestCase content fields.
         */
        TestCaseCreateRequest: {
            /** Name */
            name: string;
            /** Source Text */
            source_text: string;
        };
        /**
         * TestPlan
         * @description 一次不可变、可追溯的测试计划版本；执行仅允许使用最新版本。
         */
        TestPlan: {
            content: components["schemas"]["TestPlanContent_TestTask_"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Derived From Plan Id */
            derived_from_plan_id: string | null;
            /** Id */
            id: string;
            origin: components["schemas"]["TestPlanOrigin"];
            planning_context: components["schemas"]["TestPlanPlanningContext"];
            /** Test Case Id */
            test_case_id: string;
            /** Version Number */
            version_number: number;
        };
        /** TestPlanContent[TestTaskDefinition] */
        TestPlanContent_TestTaskDefinition_: {
            /** Assumptions */
            assumptions: string[];
            /** Setup Steps */
            setup_steps: string[];
            /** Tasks */
            tasks: components["schemas"]["TestTaskDefinition"][];
            /** Title */
            title: string;
        };
        /** TestPlanContent[TestTask] */
        TestPlanContent_TestTask_: {
            /** Assumptions */
            assumptions: string[];
            /** Setup Steps */
            setup_steps: string[];
            /** Tasks */
            tasks: components["schemas"]["TestTask"][];
            /** Title */
            title: string;
        };
        /**
         * TestPlanOrigin
         * @description 计划版本的产生方式，用于区分模型规划与人工修订历史。
         * @enum {string}
         */
        TestPlanOrigin: "planning" | "replanning" | "manual_revision";
        /**
         * TestPlanPlanningContext
         * @description 计划创建时冻结的输入与模型审计事实，不参与后续版本覆盖。
         */
        TestPlanPlanningContext: {
            device_info: components["schemas"]["DeviceInfo"] | null;
            planning_model: components["schemas"]["LLMProfileSnapshot"];
            /** Planning Prompt Version */
            planning_prompt_version: string;
            test_case_content: components["schemas"]["TestCaseContent"];
        };
        /**
         * TestRun
         * @description 一次已确认计划在单台设备上的执行聚合根。
         */
        TestRun: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Device Id */
            device_id: string;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["TestRunStatus"];
            /** Test Plan Id */
            test_plan_id: string;
            verdict: components["schemas"]["TestRunVerdict"] | null;
        };
        /** TestRunCreateRequest */
        TestRunCreateRequest: {
            /**
             * Assumptions Confirmed
             * @constant
             */
            assumptions_confirmed: true;
            /** Device Id */
            device_id: string;
            /** Test Plan Id */
            test_plan_id: string;
        };
        /**
         * TestRunDetail
         * @description 执行信息家族的完整查询组合，由 repository 装配并供执行/API 消费。
         */
        TestRunDetail: {
            run: components["schemas"]["TestRun"];
            snapshot: components["schemas"]["TestRunSnapshot"];
            /** Task Runs */
            task_runs: components["schemas"]["TaskRun"][];
            test_plan: components["schemas"]["TestPlan"];
        };
        /**
         * TestRunReport
         * @description 导出边界的完整报告组合；canonical detail 中的事实不会在顶层复制。
         */
        TestRunReport: {
            /** Artifacts */
            artifacts: components["schemas"]["Artifact"][];
            detail: components["schemas"]["TestRunDetail"];
            /** Events */
            events: components["schemas"]["StoredRunEvent"][];
        };
        /**
         * TestRunSnapshot
         * @description RunService 在 TestRun 创建时冻结且执行器必须遵守的环境事实。
         */
        TestRunSnapshot: {
            act_model: components["schemas"]["LLMProfileSnapshot"];
            /** Act Prompt Version */
            act_prompt_version: string;
            /** App Version */
            app_version: string;
            device_environment: components["schemas"]["DeviceEnvironmentSnapshot"];
            /**
             * Execution Protocol Version
             * @constant
             */
            execution_protocol_version: "1";
            judge_model: components["schemas"]["LLMProfileSnapshot"];
            /** Judge Prompt Version */
            judge_prompt_version: string;
            tool_catalog: components["schemas"]["ToolCatalogSnapshot"];
        };
        /**
         * TestRunStatus
         * @description TestRun 的持久化生命周期阶段；取消由终态 verdict 表达。
         * @enum {string}
         */
        TestRunStatus: "pending" | "running" | "finished";
        /**
         * TestRunVerdict
         * @description 整个 TestRun 的确定性结论，而非模型生成的自然语言判断。
         * @enum {string}
         */
        TestRunVerdict: "PASS" | "FAIL" | "BLOCKED" | "CANCELLED";
        /**
         * TestTask
         * @description 已获得不可变身份的计划任务；只存在于持久化 TestPlan 版本内。
         */
        TestTask: {
            definition: components["schemas"]["TestTaskDefinition"];
            /** Test Task Id */
            test_task_id: string;
        };
        /**
         * TestTaskDefinition
         * @description 没有身份的语义任务定义；模型或人工编辑先产生该结构。
         */
        TestTaskDefinition: {
            /** Goal */
            goal: string;
            /** Max Cycles */
            max_cycles: number;
            /** Success Criteria */
            success_criteria: string[];
            /** Title */
            title: string;
            type: components["schemas"]["TestTaskType"];
        };
        /**
         * TestTaskType
         * @description 计划任务的业务类型；执行过程据此选择 Agent activity。
         * @enum {string}
         */
        TestTaskType: "act" | "judge";
        /**
         * ToolCapability
         * @description 一个最终可用工具的声明事实，由合并后的 Catalog 投影产生。
         */
        ToolCapability: {
            /** Changes Device State */
            changes_device_state: boolean;
            /** Description */
            description: string;
            /** Input Schema */
            input_schema: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Scopes */
            scopes: components["schemas"]["AgentActivity"][];
        };
        /**
         * ToolCatalogSnapshot
         * @description 某台设备在 TestRun 创建时冻结的最终工具目录审计事实。
         */
        ToolCatalogSnapshot: {
            /** Tools */
            tools: components["schemas"]["ToolCapability"][];
        };
        /**
         * ToolStartedEvent
         * @description 工具通过取消安全边界并即将执行的事实。
         */
        ToolStartedEvent: {
            /** Call Id */
            call_id: string;
            /** Task Run Id */
            task_run_id: string | null;
            /** Test Run Id */
            test_run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool.started";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_artifact_api_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored artifact content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "image/png": string;
                    "text/html": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_devices_api_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_DeviceResponse_"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_device_api_devices__device_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_test_runs_api_runs_get: {
        parameters: {
            query?: {
                test_case_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_TestRun_"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    create_test_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestRunCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestRun"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_test_run_api_runs__test_run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestRunDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    cancel_test_run_api_runs__test_run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation request accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_run_events_api_runs__test_run_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                test_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_StoredRunEvent_"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    export_test_run_report_api_runs__test_run_id__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_test_run_report_api_runs__test_run_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestRunReport"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    stream_run_events_api_runs__test_run_id__stream_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "Last-Event-ID"?: number | null;
            };
            path: {
                test_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent run events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_test_cases_api_test_cases_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_TestCase_"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    create_test_case_api_test_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestCaseCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCase"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_test_case_api_test_cases__test_case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCase"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_test_plans_api_test_cases__test_case_id__plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_TestPlan_"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    generate_plan_api_test_cases__test_case_id__plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeneratePlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestPlan"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    revise_test_plan_api_test_plans__test_plan_id__revisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviseTestPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestPlan"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
