/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_api_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_api_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device */
        get: operations["get_device_api_devices__device_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Test Runs */
        get: operations["list_test_runs_api_runs_get"];
        put?: never;
        /** Create Test Run */
        post: operations["create_test_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{test_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Test Run */
        get: operations["get_test_run_api_runs__test_run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{test_run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Test Run */
        post: operations["cancel_test_run_api_runs__test_run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{test_run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Run Events */
        get: operations["list_run_events_api_runs__test_run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{test_run_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Test Run Report */
        post: operations["export_test_run_report_api_runs__test_run_id__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{test_run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Test Run Report */
        get: operations["get_test_run_report_api_runs__test_run_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{test_run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run Events */
        get: operations["stream_run_events_api_runs__test_run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Test Cases */
        get: operations["list_test_cases_api_test_cases_get"];
        put?: never;
        /** Create Test Case */
        post: operations["create_test_case_api_test_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test-cases/{test_case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Test Case */
        get: operations["get_test_case_api_test_cases__test_case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test-cases/{test_case_id}/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Test Plans */
        get: operations["list_test_plans_api_test_cases__test_case_id__plans_get"];
        put?: never;
        /** Generate Plan */
        post: operations["generate_plan_api_test_cases__test_case_id__plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test-plans/{test_plan_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revise Test Plan */
        post: operations["revise_test_plan_api_test_plans__test_plan_id__revisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentActivity
         * @enum {string}
         */
        AgentActivity: "planning" | "act" | "judge";
        /** ApiError */
        ApiError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** Artifact */
        Artifact: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Mime Type */
            mime_type: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Task Run Id */
            task_run_id: string | null;
            /** Test Run Id */
            test_run_id: string | null;
            type: components["schemas"]["ArtifactType"];
        };
        /**
         * ArtifactType
         * @enum {string}
         */
        ArtifactType: "screenshot" | "json_export" | "html_export";
        /** CycleStartedEvent */
        CycleStartedEvent: {
            /** Cycle Count */
            cycle_count: number;
            /** Task Run Id */
            task_run_id: string | null;
            /** Test Run Id */
            test_run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "cycle.started";
        };
        /** DeviceEnvironmentSnapshot */
        DeviceEnvironmentSnapshot: {
            health: components["schemas"]["DeviceHealth"];
            info: components["schemas"]["DeviceInfo"] | null;
            /** Provider */
            provider: string;
        };
        /** DeviceHealth */
        DeviceHealth: {
            /** Available */
            available: boolean;
            /** Message */
            message: string;
        };
        /** DeviceInfo */
        DeviceInfo: {
            /** Locale */
            locale: string | null;
            /** Model */
            model: string | null;
            /** Resolution */
            resolution: string | null;
        };
        /** DeviceView */
        DeviceView: {
            /** Device Id */
            device_id: string;
            health: components["schemas"]["DeviceHealth"];
            info: components["schemas"]["DeviceInfo"] | null;
            /** Provider */
            provider: string;
            tool_catalog: components["schemas"]["ToolCatalogSnapshot"] | null;
        };
        /** ExecutionErrorEvent */
        ExecutionErrorEvent: {
            /** Message */
            message: string;
            reason_code: components["schemas"]["ReasonCode"];
            /** Task Run Id */
            task_run_id: string | null;
            /** Test Run Id */
            test_run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "execution.error";
        };
        /** GeneratePlanRequest */
        GeneratePlanRequest: {
            /** Device Id */
            device_id: string;
        };
        /** LLMProfileSnapshot */
        LLMProfileSnapshot: {
            /** Base Url */
            base_url: string | null;
            /** Model */
            model: string;
            /** Profile Id */
            profile_id: string;
            /** Provider */
            provider: string;
            /** Temperature */
            temperature: number;
            /** Timeout Seconds */
            timeout_seconds: number;
        };
        /** MessageAppendedEvent */
        MessageAppendedEvent: {
            /** Message */
            message: components["schemas"]["RunSystemMessage"] | components["schemas"]["RunHumanMessage"] | components["schemas"]["RunAIMessage"] | components["schemas"]["RunToolMessage"];
            /** Task Run Id */
            task_run_id: string | null;
            /** Test Run Id */
            test_run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "message.appended";
        };
        /** MessageValidationFailedEvent */
        MessageValidationFailedEvent: {
            /** Attempt */
            attempt: number;
            /** Message Id */
            message_id: string;
            /** Reason */
            reason: string;
            /** Task Run Id */
            task_run_id: string | null;
            /** Test Run Id */
            test_run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "message.validation_failed";
        };
        /** PageResponse[DeviceView] */
        PageResponse_DeviceView_: {
            /** Items */
            items: components["schemas"]["DeviceView"][];
            /** Total */
            total: number;
        };
        /** PageResponse[StoredRunEvent] */
        PageResponse_StoredRunEvent_: {
            /** Items */
            items: components["schemas"]["StoredRunEvent"][];
            /** Total */
            total: number;
        };
        /** PageResponse[TestCase] */
        PageResponse_TestCase_: {
            /** Items */
            items: components["schemas"]["TestCase"][];
            /** Total */
            total: number;
        };
        /** PageResponse[TestPlan] */
        PageResponse_TestPlan_: {
            /** Items */
            items: components["schemas"]["TestPlan"][];
            /** Total */
            total: number;
        };
        /** PageResponse[TestRun] */
        PageResponse_TestRun_: {
            /** Items */
            items: components["schemas"]["TestRun"][];
            /** Total */
            total: number;
        };
        /**
         * ReasonCode
         * @enum {string}
         */
        ReasonCode: "completed" | "assertion_failed" | "goal_unreachable" | "cycle_limit" | "device_unavailable" | "capture_failed" | "model_unavailable" | "invalid_model_response" | "agent_blocked" | "tool_failed" | "process_restarted" | "global_fail_fast" | "user_cancelled" | "unexpected_error";
        /** ReportExportRequest */
        ReportExportRequest: {
            /**
             * Format
             * @enum {string}
             */
            format: "json" | "html";
        };
        /** ReviseTestPlanRequest */
        ReviseTestPlanRequest: {
            content: components["schemas"]["TestPlanContent_TestTaskDefinition_"];
        };
        /** RunAIMessage */
        RunAIMessage: {
            /** Content */
            content: (components["schemas"]["RunTextBlock"] | components["schemas"]["RunImageArtifactBlock"])[];
            /** Invalid Tool Calls */
            invalid_tool_calls: components["schemas"]["RunInvalidToolCall"][];
            /** Message Id */
            message_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "ai";
            /** Tool Calls */
            tool_calls: components["schemas"]["RunToolCall"][];
        };
        /** RunHumanMessage */
        RunHumanMessage: {
            /** Content */
            content: (components["schemas"]["RunTextBlock"] | components["schemas"]["RunImageArtifactBlock"])[];
            /** Message Id */
            message_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "human";
        };
        /** RunImageArtifactBlock */
        RunImageArtifactBlock: {
            /** Artifact Id */
            artifact_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "image_artifact";
        };
        /**
         * RunInvalidToolCall
         * @description Stable public fields from LangChain's finalized InvalidToolCall.
         */
        RunInvalidToolCall: {
            /** Arguments */
            arguments: string | null;
            /** Error */
            error: string | null;
            /** Id */
            id: string | null;
            /** Name */
            name: string | null;
        };
        /** RunLifecycleEvent */
        RunLifecycleEvent: {
            /** Task Run Id */
            task_run_id: string | null;
            /** Test Run Id */
            test_run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.cancelled" | "run.finished" | "run.started";
        };
        /** RunSystemMessage */
        RunSystemMessage: {
            /** Content */
            content: (components["schemas"]["RunTextBlock"] | components["schemas"]["RunImageArtifactBlock"])[];
            /** Message Id */
            message_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "system";
        };
        /** RunTextBlock */
        RunTextBlock: {
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
        };
        /** RunToolCall */
        RunToolCall: {
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** RunToolMessage */
        RunToolMessage: {
            /** Content */
            content: (components["schemas"]["RunTextBlock"] | components["schemas"]["RunImageArtifactBlock"])[];
            /** Message Id */
            message_id: string;
            /** Name */
            name: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "tool";
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "error";
            /** Tool Call Id */
            tool_call_id: string;
        };
        /** StoredRunEvent */
        StoredRunEvent: {
            /** Event */
            event: components["schemas"]["MessageAppendedEvent"] | components["schemas"]["MessageValidationFailedEvent"] | components["schemas"]["RunLifecycleEvent"] | components["schemas"]["TaskLifecycleEvent"] | components["schemas"]["CycleStartedEvent"] | components["schemas"]["ToolStartedEvent"] | components["schemas"]["ExecutionErrorEvent"] | components["schemas"]["TasksSkippedEvent"];
            /** Event Id */
            event_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Sequence */
            sequence: number;
        };
        /** TaskLifecycleEvent */
        TaskLifecycleEvent: {
            /** Task Run Id */
            task_run_id: string | null;
            /** Test Run Id */
            test_run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "task.finished" | "task.started";
        };
        /** TaskRun */
        TaskRun: {
            /** Cycle Count */
            cycle_count: number;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            result: components["schemas"]["TaskRunResult"] | null;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["TaskRunStatus"];
            /** Test Run Id */
            test_run_id: string;
            /** Test Task Id */
            test_task_id: string;
        };
        /** TaskRunResult */
        TaskRunResult: {
            /** Evidence Artifact Ids */
            evidence_artifact_ids: string[];
            reason_code: components["schemas"]["ReasonCode"];
            /** Summary */
            summary: string;
        };
        /**
         * TaskRunStatus
         * @enum {string}
         */
        TaskRunStatus: "running" | "passed" | "failed" | "blocked" | "skipped";
        /** TasksSkippedEvent */
        TasksSkippedEvent: {
            /** Task Run Id */
            task_run_id: string | null;
            /** Task Run Ids */
            task_run_ids: string[];
            /** Test Run Id */
            test_run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tasks.skipped";
        };
        /** TestCase */
        TestCase: {
            content: components["schemas"]["TestCaseContent"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
        };
        /** TestCaseContent */
        TestCaseContent: {
            /** Name */
            name: string;
            /** Source Text */
            source_text: string;
        };
        /**
         * TestCaseCreateRequest
         * @description Command name over the canonical TestCase content fields.
         */
        TestCaseCreateRequest: {
            /** Name */
            name: string;
            /** Source Text */
            source_text: string;
        };
        /** TestPlan */
        TestPlan: {
            content: components["schemas"]["TestPlanContent_TestTask_"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Derived From Plan Id */
            derived_from_plan_id: string | null;
            /** Id */
            id: string;
            origin: components["schemas"]["TestPlanOrigin"];
            planning_context: components["schemas"]["TestPlanPlanningContext"];
            /** Test Case Id */
            test_case_id: string;
            /** Version Number */
            version_number: number;
        };
        /** TestPlanContent[TestTaskDefinition] */
        TestPlanContent_TestTaskDefinition_: {
            /** Assumptions */
            assumptions: string[];
            /** Setup Steps */
            setup_steps: string[];
            /** Tasks */
            tasks: components["schemas"]["TestTaskDefinition"][];
            /** Title */
            title: string;
        };
        /** TestPlanContent[TestTask] */
        TestPlanContent_TestTask_: {
            /** Assumptions */
            assumptions: string[];
            /** Setup Steps */
            setup_steps: string[];
            /** Tasks */
            tasks: components["schemas"]["TestTask"][];
            /** Title */
            title: string;
        };
        /**
         * TestPlanOrigin
         * @enum {string}
         */
        TestPlanOrigin: "planning" | "replanning" | "manual_revision";
        /** TestPlanPlanningContext */
        TestPlanPlanningContext: {
            device_info: components["schemas"]["DeviceInfo"] | null;
            planning_model: components["schemas"]["LLMProfileSnapshot"];
            /** Planning Prompt Version */
            planning_prompt_version: string;
            test_case_content: components["schemas"]["TestCaseContent"];
        };
        /** TestRun */
        TestRun: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Device Id */
            device_id: string;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["TestRunStatus"];
            /** Test Plan Id */
            test_plan_id: string;
            verdict: components["schemas"]["TestRunVerdict"] | null;
        };
        /** TestRunCreateRequest */
        TestRunCreateRequest: {
            /**
             * Assumptions Confirmed
             * @constant
             */
            assumptions_confirmed: true;
            /** Device Id */
            device_id: string;
            /** Test Plan Id */
            test_plan_id: string;
        };
        /** TestRunDetail */
        TestRunDetail: {
            run: components["schemas"]["TestRun"];
            snapshot: components["schemas"]["TestRunSnapshot"];
            /** Task Runs */
            task_runs: components["schemas"]["TaskRun"][];
            test_plan: components["schemas"]["TestPlan"];
        };
        /** TestRunReport */
        TestRunReport: {
            /** Artifacts */
            artifacts: components["schemas"]["Artifact"][];
            detail: components["schemas"]["TestRunDetail"];
            /** Events */
            events: components["schemas"]["StoredRunEvent"][];
        };
        /** TestRunSnapshot */
        TestRunSnapshot: {
            act_model: components["schemas"]["LLMProfileSnapshot"];
            /** Act Prompt Version */
            act_prompt_version: string;
            /** App Version */
            app_version: string;
            device_environment: components["schemas"]["DeviceEnvironmentSnapshot"];
            /**
             * Execution Protocol Version
             * @constant
             */
            execution_protocol_version: "1";
            judge_model: components["schemas"]["LLMProfileSnapshot"];
            /** Judge Prompt Version */
            judge_prompt_version: string;
            tool_catalog: components["schemas"]["ToolCatalogSnapshot"];
        };
        /**
         * TestRunStatus
         * @enum {string}
         */
        TestRunStatus: "pending" | "running" | "finished";
        /**
         * TestRunVerdict
         * @enum {string}
         */
        TestRunVerdict: "PASS" | "FAIL" | "BLOCKED" | "CANCELLED";
        /** TestTask */
        TestTask: {
            definition: components["schemas"]["TestTaskDefinition"];
            /** Test Task Id */
            test_task_id: string;
        };
        /** TestTaskDefinition */
        TestTaskDefinition: {
            /** Goal */
            goal: string;
            /** Max Cycles */
            max_cycles: number;
            /** Success Criteria */
            success_criteria: string[];
            /** Title */
            title: string;
            type: components["schemas"]["TestTaskType"];
        };
        /**
         * TestTaskType
         * @enum {string}
         */
        TestTaskType: "act" | "judge";
        /** ToolCapability */
        ToolCapability: {
            /** Changes Device State */
            changes_device_state: boolean;
            /** Description */
            description: string;
            /** Input Schema */
            input_schema: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Scopes */
            scopes: components["schemas"]["AgentActivity"][];
        };
        /** ToolCatalogSnapshot */
        ToolCatalogSnapshot: {
            /** Tools */
            tools: components["schemas"]["ToolCapability"][];
        };
        /** ToolStartedEvent */
        ToolStartedEvent: {
            /** Call Id */
            call_id: string;
            /** Task Run Id */
            task_run_id: string | null;
            /** Test Run Id */
            test_run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool.started";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_artifact_api_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored artifact content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "image/png": string;
                    "text/html": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_devices_api_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_DeviceView_"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_device_api_devices__device_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_test_runs_api_runs_get: {
        parameters: {
            query?: {
                test_case_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_TestRun_"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    create_test_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestRunCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestRun"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_test_run_api_runs__test_run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestRunDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    cancel_test_run_api_runs__test_run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation request accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_run_events_api_runs__test_run_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                test_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_StoredRunEvent_"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    export_test_run_report_api_runs__test_run_id__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_test_run_report_api_runs__test_run_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestRunReport"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    stream_run_events_api_runs__test_run_id__stream_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "Last-Event-ID"?: number | null;
            };
            path: {
                test_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent run events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_test_cases_api_test_cases_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_TestCase_"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    create_test_case_api_test_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestCaseCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCase"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_test_case_api_test_cases__test_case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCase"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_test_plans_api_test_cases__test_case_id__plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_TestPlan_"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    generate_plan_api_test_cases__test_case_id__plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeneratePlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestPlan"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    revise_test_plan_api_test_plans__test_plan_id__revisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviseTestPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestPlan"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
